const {$M,$V} = require('../lib/nitrile-preview-sylvester.js');

var V = $V( [1,1] );
var V2 = $V( [4,2] );
console.log(V);
var flag = V.eql(V2);
console.log(flag);
var V3 = V.toUnitVector();
console.log(V3);
var V4 = $V( [0,4] );
var angle = V.angleFrom(V4);
console.log(angle/Math.PI*180);
var V5 = $V( [-1,-1] );
var flag = V.isParallelTo(V5);
console.log('isparellelto: ',flag);
var flag = V.isAntiparallelTo(V5);
console.log('isantiparellelto: ',flag);
var flag = V.isPerpendicularTo(V5);
console.log('isperpendicularto: ',flag);
var V6 = $V( [-1,1] );
var flag = V.isPerpendicularTo(V6);
console.log('isperpendicularto: ',flag);
var newV = V.add(V6);
console.log('add: newV: ',newV);
var newV = V.subtract(V6);
console.log('subtract: newV: ',newV);
var newV = V.multiply(5);
console.log('multiply: newV: ',newV);

var V1 = $V([1,0,0]);
var V2 = $V([0,1,0]);
var newV = V1.cross(V2);
console.log('newV: ',newV);
var point = $V([1,0,2]);
var dist = V1.distanceFrom(point);
console.log('dist: ',dist);
