#!/bin/bash
#echo $1
#node -e "console.log($1)"
node -e "const { NitrilePreviewNode } = require ('$HOME/github/nitrile-preview/lib/nitrile-preview-node'); new NitrilePreviewNode().to_lualatexja_document_async('$1').then(([f,dname,fname]) => { console.log('f',f); console.log('dname',dname); console.log('fname',fname); const compile = require('child_process').spawn('lualatex',['--interaction=scrollmode', '--output-directory='+dname, '-halt-on-error', fname]); compile.stdout.on('data',(data) => process.stdout.write(data)); compile.on('close',(code) => { console.log('compile process finished');    } ); } ).catch(err => console.log(err))"


