#!/bin/bash
#echo $1
#node -e "console.log($1)"
node -e "const { NitrilePreviewNode } = require ('$HOME/github/nitrile-preview/lib/nitrile-preview-node'); new NitrilePreviewNode().to_pdflatex_document_async('$1').then(([f,dname,fname]) => { console.log(f); console.log(dname); console.log(fname); const context = require('child_process').spawn('pdflatex',['--interaction=scrollmode', '--output-directory='+dname, '-halt-on-error', fname]); context.stdout.on('data',(data) => process.stdout.write(data)); context.on('close',(code) => { console.log('context process finished');    } ); } ).catch(err => console.log(err))"


