#!/bin/bash
#echo $1
#node -e "console.log($1)"
node -e "const { run_fontmap } = require ('../lib/nitrile-preview-utils'); run_fontmap('$*').then(f => console.log(f)).catch(err => console.log(err))"


