#!/bin/bash
echo $1
#node -e "console.log($1)"
node -e "require ('/home/james/github/nitrile-preview/lib/nitrile-preview-node').toHtml('$1').then(f => console.log(f)).catch(err => console.log(err))"


