#!/bin/bash
#echo $1
#node -e "console.log($1)"
node -e "const { NitrilePreviewNode } = require ('../lib/nitrile-preview-node'); new NitrilePreviewNode().toLatex('$1').then(f => console.log(f)).catch(err => console.log(err))"


